# Based on:
#   * https://github.com/open-webui/open-webui/blob/main/docker-compose.yaml
#   * https://docs.openwebui.com/getting-started/quick-start/ (select Docker Compose)

services:

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: nginx

  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    tty: true
    restart: unless-stopped
    # TODO: Comment out this block if you don't need support for Nvidia GPUs.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    depends_on:
      - ollama
    volumes:
      - open-webui:/app/backend/data
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - open-webui
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    ports:
      - "443:443"
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
